name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'Makefile'
      - 'data/**'
      - '.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  grpc-code-consistency:
    uses: ./.github/workflows/grpc-code-consistency.yml
    needs: lint

  test:
    uses: ./.github/workflows/test.yml
    needs:
      - lint
      - grpc-code-consistency
