name: ci

on:
  push:
    branches: ['*']
  pull_request:
    paths-ignore: ['README.md', 'Makefile', 'data/**', '.gitignore']

env:
  GO_VERSION: "1.21"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  grpc-code-consistency:
    needs: lint
    uses: ./.github/workflows/grpc-code-consistency.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  test:
    needs: [lint, grpc-code-consistency]
    uses: ./.github/workflows/test.yml
    with:
      go-version: ${{ env.GO_VERSION }}
