name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  GO_VERSION: "1.21"
  BUILD_NAME: "edge-grpc-mock-server"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cross builds
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-linux main.go
          GOOS=linux GOARCH=arm64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-linux main.go
          GOOS=darwin GOARCH=amd64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-darwin main.go
          GOOS=darwin GOARCH=arm64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-darwin main.go

      - name: Archive binaries
        run: |
          cd bin
          mkdir -p archives
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-linux.tar.gz ${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-linux
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-linux.tar.gz ${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-linux
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-darwin.tar.gz ${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-darwin
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-darwin.tar.gz ${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-darwin

      - name: Get git tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --exact-match HEAD)"

      - name: Publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_tag.outputs.tag }}
          release_name: ${{ steps.get_tag.outputs.tag }}
          prerelease: true
          file_glob: true
          file: bin/archives/*.tar.gz
          overwrite: true