name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  GO_VERSION: "1.21"
  BUILD_NAME: "edge-grpc-mock-server"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cross builds
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-linux main.go
          GOOS=linux GOARCH=arm64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-linux main.go
          GOOS=darwin GOARCH=amd64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-darwin main.go
          GOOS=darwin GOARCH=arm64 go build -o bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-darwin main.go

      - name: Archive binaries
        run: |
          mkdir -p archives
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-linux.tar.gz bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-linux
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-linux.tar.gz bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-linux
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-darwin.tar.gz bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-amd64-darwin
          tar -czvf archives/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-darwin.tar.gz bin/${{ env.BUILD_NAME }}-${GITHUB_REF#refs/tags/}-aarch64-darwin


      - name: Publish binaries
        uses: actions/upload-artifact@v2
        with:
          name: archives
          path: archives/
